Include `tox.ini` in sdist to fix tests
Include the `tox.ini` file in sdist, in order to fix a few test failures
due to an additional error message printed by tox, i.e.:

    FAILED tests/config/cli/test_parse.py::test_verbosity_guess_miss_match - AssertionError: assert 'ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /tmp/portage/dev-python/t...
    FAILED tests/config/loader/test_loader.py::test_override_incorrect[-x] - AssertionError: assert not 'ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /tmp/portage/dev-pyth...
    FAILED tests/config/loader/test_loader.py::test_override_incorrect[--override] - AssertionError: assert not 'ROOT: No tox.ini or setup.cfg or pyproject.toml found, assuming empty tox.ini at /tmp/portage/dev-pyth...