Session: use realpath when ensuring that logdir exists
This allows for having a dangling symlink `.tox` (e.g. to somewhere into
`/tmp`), and the directory will be created instead of causing an error
(because it is not a dir, but exists already):

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/py/_error.py", line 66, in checked_call
        return func(*args, **kwargs)
    FileExistsError: [Errno 17] File exists: '…/src/covimerage/.tox'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/bin/tox", line 11, in <module>
        load_entry_point('tox==2.9.1', 'console_scripts', 'tox')()
      File "/usr/lib/python3.6/site-packages/tox/session.py", line 40, in main
        retcode = Session(config).runcommand()
      File "/usr/lib/python3.6/site-packages/tox/session.py", line 337, in __init__
        config.logdir.ensure(dir=1)
      File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 530, in ensure
        return p._ensuredirs()
      File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 512, in _ensuredirs
        parent._ensuredirs()
      File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 515, in _ensuredirs
        self.mkdir()
      File "/usr/lib/python3.6/site-packages/py/_path/local.py", line 465, in mkdir
        py.error.checked_call(os.mkdir, fspath(p))
      File "/usr/lib/python3.6/site-packages/py/_error.py", line 86, in checked_call
        raise cls("%s%r" % (func.__name__, args))
    py.error.EEXIST: [File exists]: mkdir('…/src/covimerage/.tox',)