Tests: Don't assume Python 3.10 is always installed, use current Python version
See https://github.com/tox-dev/tox/pull/3089#pullrequestreview-1603222695

test_allowed_implicit_cli_envs[py310] assumed Python 3.10 is installed.
It failed without it:

    ____________________ test_allowed_implicit_cli_envs[py310] _____________________
    [gw3] linux -- Python 3.12.0 /usr/bin/python3

    env_name = 'py310'
    tox_project = <function init_fixture.<locals>._init at 0x7febd4e1ca40>

        @pytest.mark.parametrize("env_name", ["py", "py310", ".pkg"])
        def test_allowed_implicit_cli_envs(env_name: str, tox_project: ToxProjectCreator) -> None:
            proj = tox_project({"tox.ini": ""})
            outcome = proj.run("r", "-e", env_name)
    >       outcome.assert_success()

    env_name   = 'py310'
    outcome    = code: -1
    cmd: /usr/bin/python3 -m tox r -e py310
    cwd: /tmp/pytest-of-mockbuild/pytest-0/popen-gw3/test_allowed_implici...uld not find python interpreter with spec(s): py310
      py310: SKIP (0.23 seconds)
      evaluation failed :( (0.27 seconds)

    proj       = ToxProject(path=/tmp/pytest-of-mockbuild/pytest-0/popen-gw3/test_allowed_implicit_cli_envs1/p) at 140650867026656
    tox_project = <function init_fixture.<locals>._init at 0x7febd4e1ca40>

    tests/session/test_env_select.py:158:
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    self = code: -1
    cmd: /usr/bin/python3 -m tox r -e py310
    cwd: /tmp/pytest-of-mockbuild/pytest-0/popen-gw3/test_allowed_implici...uld not find python interpreter with spec(s): py310
      py310: SKIP (0.23 seconds)
      evaluation failed :( (0.27 seconds)

        def assert_success(self) -> None:
    >       assert self.success, repr(self)  # noqa: S101
    E       AssertionError: code: -1
    E         cmd: /usr/bin/python3 -m tox r -e py310
    E         cwd: /tmp/pytest-of-mockbuild/pytest-0/popen-gw3/test_allowed_implicit_cli_envs1/p
    E         standard output
    E         py310: skipped because could not find python interpreter with spec(s): py310
    E           py310: SKIP (0.23 seconds)
    E           evaluation failed :( (0.27 seconds)
    E
    E       assert False
    E        +  where False = code: -1\ncmd: /usr/bin/python3 -m tox r -e py310\ncwd: /tmp/pytest-of-mockbuild/pytest-0/popen-gw3/test_allowed_implicit_cli_envs1/p\nstandard output\npy310: skipped because could not find python interpreter with spec(s): py310\n  py310: SKIP (0.23 seconds)\n  evaluation failed :( (0.27 seconds)\n.success

    self       = code: -1
    cmd: /usr/bin/python3 -m tox r -e py310
    cwd: /tmp/pytest-of-mockbuild/pytest-0/popen-gw3/test_allowed_implici...uld not find python interpreter with spec(s): py310
      py310: SKIP (0.23 seconds)
      evaluation failed :( (0.27 seconds)

    .../usr/lib/python3.12/site-packages/tox/pytest.py:352: AssertionError

This way, we use an environment that is available (as long as the tests run on CPython).
This could be improved to support PyPy as well, but I decided to take one step at a time.