The tests actually require wheel
When wheel is not installed, several tests error like this:

    distutils.errors.DistutilsModuleError: invalid command 'bdist_wheel'
    ...
    SystemExit: error: invalid command 'bdist_wheel'

Or like this:

    ERROR Missing dependencies:
    	wheel

When the tests are executed in a virtualenv, wheel is implicitly installed,
which is why this have never happened on the CI.

List of tests that error:

     ERROR tests/tox_env/python/virtual_env/package/test_package_cmd_builder.py::test_tox_install_pkg_wheel
     ERROR tests/tox_env/python/virtual_env/package/test_package_cmd_builder.py::test_tox_install_pkg_sdist
     ERROR tests/tox_env/python/virtual_env/package/test_package_cmd_builder.py::test_install_pkg_via[p]
     ERROR tests/tox_env/python/virtual_env/package/test_package_cmd_builder.py::test_install_pkg_via[le]
     ERROR tests/tox_env/python/virtual_env/package/test_python_package_util.py::test_load_dependency_no_extra
     ERROR tests/tox_env/python/virtual_env/package/test_python_package_util.py::test_load_dependency_many_extra

Version 0.38.4 is required as this is the current version
and this is the way tox specifies the test dependencies.