docs(config): fix default value for install_command (#3126)
The `install_command` config is documented as having the default value:

  python -I -m pip install <opts> <packages>

The last two arguments are not substituable and are thus passed as is
(eg as packages to install) resulting in:

  py3-test: install_deps> python -I -m pip install -v '<opts>'
  '<packages>' '.[test]'
  ERROR: Invalid requirement: '<opts>'

Adjust the documentation to use the replaceable variables: `{opts}` and
`{packages}`.